version: "3.6"
services:
    host:
        image: upmlctf/short
        build: private
        ports:
          - "30002:80"
        restart: always
        volumes:
          - "./private/db.sqlite3:/app/db.sqlite3"

