#!yaml

category:   recon
points:     200
short:      teemoorkanetwork
name:       "TeeMoorka.Network"
author:     dmitriyp
description: >
  Наверное, вы помните о крутом стартапе ИП TeeMoorka.Net — Chatius.
  Этот чат порвал все мыслимые и не очень рекорды по количеству зарегистрированных
  за сутки пользователей и отправленных сообщений. И вот, CEO TeeMoorka.Net
  сообщил, что уже пора расширяться, и он открывает ***ООООО TeeMoorka.Network***
  Вслед за этим последовало ещё несколько малоинтересных объявлений о том,
  что скоро они запустят свою онлайн-школу по созданию крутых чатов, платные туторы
  по адаптивному деzzигну и самый защищёный ***криптотенге TeeMoorka.Coin***
  Ещё они решили развивать ЦТФ—движение и ищут работников для своего офиса, который
  уже стал популярным местом для туристов и собрал множество положительных отзывов.
  А ещё рядом с ним раньше хостили проекты по Minecraft.
  
  Не хотите примкнуть к Великим?
flags:
  -
    text:   "uctf_is_trip_advisor"