category:    stegano
points:      100
short:       "false"
name:        "Белый квадрат"
author:      nsychev
description: >
    Как мы знаем, картина Малевича «Черный квадрат» хранит все тайны мироздания. А, значит,
    пришло время — всемирно известный художник Пабло Микелавелли Кузнецов нарисовал «Белый 
    квадрат».
    
    На вопрос, спрятаны ли в нём тайны, он ответил лишь одной фразой: «Чтобы что-то спрятать,
    положите это на видное место».
attachments:
    - task.png
flags:
    -
        text: uctf_i_decoded_qrs_yes
