category:   ppc
points:     200
short:      chatius
name:       "Chatius"
author:     dmitriyp
description: >
 Все мы пользуемся интернетами. Но научно доказано, что существует класс людей,
 которые знают больше остальных. Один из таких - TeeMoor, который не верит
 всем этим людям с запада, ведь ему известно, что они пытаются разрушить нашу
 Великую страну, да и переписки он им показывать не хочет. Поэтому он 
 организовал ИП TeeMoorKa.Net и разработал собственный, самый лучший, 
 быстрый и крутой чат с нейросетями и шлюзами, который пользуется большой
 популярностью в селе TeeMoora. И этот чат настолько классный, что он показывал
 его секретные наработки губернатору своего двора, а ещё там и подарки раздают!

 Беги туда скорее, пока грязные иностранцы и его не купили!!!
url:        https://chatius-paris.ctf.upml.tech/
flags:
  -
    text:   "uctf_l0ve_pr0t3cted_ch@ts"
