category:    crypto
points:      75
short:       message
name:        "Message"
author:      nsychev
description: >
    Мы вышли на след подозреваемых в атаках на выборы в Соединенных Штатах!
    
    Ими оказались четыре пятнадцатилетних участника Ugra CTF 2018. Конечно же, мы
    установили за ними наблюдение. Однако, нам кажется, что системы перехвата данных
    бракованные — ведь они выдают какую-то дичь!
    
    Объясните, в конце концов, что тут происходит?
attachments:
    - message.txt
flags:
    -
        text: "uctfdonotuserawsms"
