category:    web
points:      50
short:       spy
name:        "Американский шпион"
author:      nsychev
description: >
    Нам поступила информация, что на наш CTF зарегистрировался не кто иной, как
    самый настоящий шпион из Пентагона! Он хочет найти всех российских хакеров,
    а, как известно, найти сразу всех можно только в одном месте — на UPML CTF!
    
    Мы проверили все команды, и не увидели шпиона. Может быть, вы более внимательны?
    Всё, что от вас нужно — название команды-шпиона. Дальше мы сами!
flags:
    -
        text: "uctf_hidden_sc0r3boa4d_team"
