category:    admin
points:      200
short:       telegram
name:        "Telegram"
author:      nsychev
description: >
    Я — успешный современный бизнесмен, эксперт по мемам и вообще крутой парень! Не верите?
    Вчера я [закупил немного биткоинов](https://sun9-6.userapi.com/c543109/v543109883/3a562/z7TqSaQ0AU4.jpg),
    а, значит, завтра уже стану миллиардером!
    
    Сегодня я узнал о том, что Павел Дуров раздает гранты, поэтому поднял свой прокси-сервер для телеграма.
    Заказал современный сервер на Pentium-III в Париже, запустил danted и готово!
    
    Однако, так как денег нет, пришлось хостить прокси вместе с серверами майнкрафта и базой флагов. Но не 
    думаю, что это окажется проблемой.
    
    Короче, жду всех клиентов :)
url: https://t.me/socks?server=socks.ctf.upml.tech&port=2080&user=proxy&pass=TelegaTop
flags:
    -
        text: "uctf_lock_proxy_users_properly"

