category:    web
points:      150
short:       secrets
name:        "Secret Keeper"
author:      nsychev
description: >
    Я не очень доверяю людям. Полагаю, ты тоже. Но, если так, то
    с кем можно делиться самыми тайными секретами?

    Проблема решена — я сделал телеграм-бота, который хранит секреты.
    Но, как всем известно, хакеры могут взломать всё, да и сам
    телеграм может прослушиваться (это же вам не Chatius).

    Поэтому я совершил революционный прорыв — отказался от базы данных.
    Всё верно — бот не запоминает ваши секреты. Только так обеспечивается 146% безопасность системы.

    Я уже пользуюсь хранителем! А вы?
url: "https://t.me/thesecretestbot"
flags:
    -
        text: "uctf_t0k3n_l34k_found"

